### ISSUE TITLE
jnm_jupyternotebook/notebooks/collision_avoidanceを実行してロボット動かなかった。

### ISSUE THREAD

**Issue by cuigaochao** [rt-net/jnm_jupyternotebook#17]
# 不具合の概要
jnmouse_jp451_v3.zipにより、または
https://github.com/rt-net/jnm_jupyternotebook/blob/master/notebooks/collision_avoidance/live_demo.ipynb
により、live_demo.ipynbやlive_demo_resnet18.ipynbなど実行して、jnmが移動しません。エラーも出ません。
basic_motion、object_following、road_followingが問題ありません。

# 実行環境

- OS: 
- ソフトのバージョン: 

# 再現方法

1. data_collection.ipynb を実行する
2. train_model.ipynb を実行する
3. live_demo.ipynb を実行する
4. 不具合が発生する

# 期待する動作

# ログ・画像

```sh
# コマンド実行ログがあればここに貼り付けてください
```

# その他

どうすれば良いでしょうか？
どうぞよろしくお願いいたします。

**Comment by Tiryoh** [comment]
コメントが遅くなりました。問題は解決しましたか？

以下のセルまで実行したときにカメラ映像は表示されていますか？

![image](https://user-images.githubusercontent.com/3256629/147532980-22b4f276-4eb5-41d6-bbe6-a7473d87d160.png)

それより先のセルを実行すると止まってしまいます。

どのセルまで実行してもロボットが動かなかったのかわかるようなスクリーンショットがあれば共有してもらえると助かります。

その他には他のNotebookが実行中になっていてメモリが不足していることも原因として考えら
れます。使わないNotebookは終了してから実行してみてください。

![Screenshot from 2021-12-28 14-56-03](https://user-images.githubusercontent.com/3256629/147532890-7bfc1a0b-e5e8-4439-8963-1de783dbb536.png)
